apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance
  template:
    metadata:
      labels:
        app: attendance
    spec:
      containers:
      - name: attendance-container
        image: attendance-system_web
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-service
spec:
  type: NodePort
  selector:
    app: attendance
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30090

